### ISSUE TITLE
Update to use latest BotBuilder version

### ISSUE THREAD

**Issue by ejadib** [Microsoft/BotBuilder-Location#107]
The version that is currently using is really old and in the last version were several changes on how Prompts works that might be affecting this.

**Comment by mattcowen** [comment]
There appears to be at least one problem that is resolved by updating to BotBuilder 3.8.0 which is the latest as of now. The issue:
If I enter a UK postcode the PromptDialog.Confirm fails in with a missingmethodexception when PromptForSingleAddressSelection is called in RichLocationRetrieveDialog.

**Comment by garypretty** [comment]
I am still seeing a missing method exception when using v2 of the location dialog with v3.8 of the bot builder.

**Comment by kgrashad** [comment]
Thanks all, we will release an update soon using the latest botbuilder sdk.

**Comment by garypretty** [comment]
Thanks. Do you have a potential timescale on this? Could you maybe get a fix onto an alpha branch Niger package?

I am looking to do a demo in a presentation of Location Control V2 and Speech in bot framework, but right now because of the problem I can't.

If I know you won't be able to get this out quickly then I'll fork the repo and see if I can fix, so no worries if you guys are stacked.

Great work on V2 btw!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by camer314** [comment]
@garypretty A straight recompile with v3.8 fixes the issue if you wanted to go that route rather than waiting for nuget release

**Comment by ejadib** [comment]
https://github.com/Microsoft/BotBuilder-Location/pull/109

**Comment by kgrashad** [comment]
Released https://www.nuget.org/packages/Microsoft.Bot.Builder.Location?NormalizedVersion=2.1.0
